In [1]:
import pandas as pd
import numpy as np

In [2]:
fb_df = pd.read_csv("data-temp/fb_data_langid_semiprocessed.csv", sep="\t", encoding="utf-8-sig")

In [3]:
# fb_df[fb_df["description"].str.len() > 3 & fb_df["location"].notnull()]
fb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11829 entries, 0 to 11828
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   11829 non-null  int64
 1   name         11829 non-null  object
 2   link         11829 non-null  object
 3   profile_pic  11826 non-null  object
 4   role         5 non-null      object
 5   id           11829 non-null  object
 6   type         11826 non-null  object
 7   labels       11829 non-null  object
 8   joined       11821 non-null  object
 9   description  6922 non-null   object
 10  lang         6923 non-null   object
 11  location     3361 non-null   object
 12  occupation   196 non-null    object
 13  misc_ents    509 non-null    object
 14  other_ents   74 non-null     object
 15  untagged     1019 non-null   object
dtypes: int64(1), object(15)
memory usage: 1.4+ MB

In [5]:
fb_df["lang"].value_counts()

en    4581
id    1320
pt     525
es     343
vi      78
be      29
tr      24
ar       9
ru       5
bg       5
ko       3
he       1
Name: lang, dtype: int64

In [12]:
import numpy


fb_df.iat[8, 12] is numpy.nan

True

In [13]:
unprocessed_df = fb_df[(fb_df["description"].str.len() > 3) & (fb_df["location"].isnull()) & (fb_df["occupation"].isnull()) & (fb_df["misc_ents"].isnull()) & (fb_df["other_ents"].isnull()) & (fb_df["untagged"].isnull())]

In [14]:
unprocessed_df["description"].describe()

count                  1976
unique                 1713
top       Chicago, Illinois
freq                      9
Name: description, dtype: object

In [15]:
value_counts_df = unprocessed_df["description"].value_counts()
value_counts_df.to_csv("data-temp/fb_data_unprocessed_value_frequencies.csv", sep="\t")

In [16]:
value_counts_descr_full = fb_df["description"].value_counts()
value_freqs_descr_full = value_counts_descr_full / fb_df["description"].count()
values_descr_df = pd.merge(value_counts_descr_full, value_freqs_descr_full, left_index=True, right_index=True)
values_descr_df.to_csv("data-temp/fb_data_descr_values.csv", sep="\t")

In [17]:
unprocessed_df["location"] = unprocessed_df["description"]

e:\Users\Eric\miniconda3\envs\arcgis_env\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [18]:
fb_df_v2 = fb_df
fb_df_v2.update(unprocessed_df)

In [19]:
fb_df_v2.head(20)

,Unnamed: 0,name,link,profile_pic,role,id,type,labels,joined,description,lang,location,occupation,misc_ents,other_ents,untagged
0,0.0,Wes W Parker,https://www.facebook.com/wes.parker.9277,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.18...,admin/moderator,9arFVr8dkfuuDextavLKFH,UserAccount,['UserAccount'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,Kristen Fitzpatrick,https://www.facebook.com/kristen.fitzpatrick.12,https://scontent.ffcm1-1.fna.fbcdn.net/v/t39.3...,admin/moderator,mjHRdrVWvSJ2onFjyR65wy,UserAccount,['UserAccount'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,Jorene Monares Dela Cruz,https://www.facebook.com/jorene.monaresdelacruz,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.64...,NaN,K9vNtK9UcY6bmkNtgkG93u,UserAccount,['UserAccount'],Joined last Thursday,Works at Facebook App,en,Facebook App,NaN,NaN,NaN,NaN
3,3.0,Huong Giang Nguyen,https://www.facebook.com/profile.php?id=100023...,https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.64...,NaN,iW36iPpvH9JMDdL6Nswg35,UserAccount,['UserAccount'],Joined last Thursday,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,Khanavin Quebec,https://www.facebook.com/profile.php?id=100076...,https://scontent.ffcm1-1.fna.fbcdn.net/v/t39.3...,NaN,LbiErEjx37bFqHJbpxMj4u,UserAccount,['UserAccount'],Joined on Thursday,"Driver at Valley Golf Cainta, Rizal",en,Rizal,Valley Golf Cainta,NaN,NaN,NaN
5,5.0,Jtizzle Thomas,https://www.facebook.com/jtizzle.thomas,https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.64...,NaN,bw4RM8txR8uBYztQFW8N3V,UserAccount,['UserAccount'],Joined about a week ago,Middle Georgia Technical College,en,Middle Georgia Technical College,NaN,NaN,NaN,NaN
6,6.0,Fachri Putra,https://www.facebook.com/fachri.putrabenua,https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.64...,NaN,2HhoSj4k2PrdpdWCKcDpWU,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.0,Arvind Shodha,https://www.facebook.com/arvind.shodha.16,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.64...,NaN,iETzqxanxpZna6BbDmiqdz,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8.0,Rambo Buteng,https://www.facebook.com/rambo.boteng,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.64...,NaN,baofYjPRXFQBuDU6ETTuxB,UserAccount,['UserAccount'],Joined about a week ago,Works at Self-Employed,en,NaN,NaN,NaN,NaN,Self-Employed
9,9.0,Nguyen Le Ngan,https://www.facebook.com/profile.php?id=100077...,https://scontent.ffcm1-2.fna.fbcdn.net/v/t39.3...,NaN,jvAJNc9DZZMEB442NxQeVf,UserAccount,['UserAccount'],Joined about a week ago,Trường Đại Học Trà Vinh,vi,Trường Đại Học Trà Vinh,NaN,NaN,NaN,NaN
10,10.0,ိဝါ ဝါ,https://www.facebook.com/profile.php?id=100026...,https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.64...,NaN,FfefmYgwUVVRWJWrLkpr8U,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11.0,Ta Hoang Son,https://www.facebook.com/profile.php?id=100077...,https://scontent.ffcm1-2.fna.fbcdn.net/v/t39.3...,NaN,PBsxMvYJy7RXzae6ERh6LB,UserAccount,['UserAccount'],Joined about a week ago,"Works at J. Riley Williams, PLC",en,PLC,NaN,J. Riley Williams,NaN,NaN
12,12.0,Angelo Bonife,https://www.facebook.com/angelo.bonife.5,https://scontent.ffcm1-1.fna.fbcdn.net/v/t39.3...,NaN,XaKoKRExPTmmu48s9Qqtqz,UserAccount,['UserAccount'],Joined on Wednesday,MegaPatrol at Security guard,en,NaN,NaN,NaN,NaN,Security guard
13,13.0,Nay Lin,https://www.facebook.com/profile.php?id=100016...,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.18...,NaN,THNXQz3cbbB5FrybbUQLfs,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14.0,Bocboc Jl,https://www.facebook.com/bocboc.jl,https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.64...,NaN,E8KNXjJpzvgGRywPBqZpQn,UserAccount,['UserAccount'],Joined about a week ago,Works at The Krusty Krab,en,The Krusty Krab,NaN,NaN,NaN,NaN
15,15.0,MD Nur Alom,https://www.facebook.com/profile.php?id=100060...,https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.64...,NaN,T7Un3guzGgwtECAdsSCYPX,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16.0,Iyong Gordes Pramuditha,https://www.facebook.com/iyonx.pramuditha,https://scontent.ffcm1-1.fna.fbcdn.net/v/t39.3...,NaN,NNQ4oqg3thpBKeU2rcQXkB,UserAccount,['UserAccount'],Joined about a week ago,Manager at Di Jongol,en,NaN,NaN,Di Jongol,NaN,NaN
17,17.0,Md Najmul Hasan Ratul,https://www.facebook.com/mdnajmul.hasanratul.3,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.18...,NaN,j8St5Z5njbGqDHj8YA9FwX,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18.0,Vuong Nguyen,https://www.facebook.com/profile.php?id=100052...,https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.30...,NaN,Ue4Q93oLQuRDWAGFKMmKah,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19.0,Dũng Hoàng,https://www.facebook.com/profile.php?id=100050...,https://scontent.ffcm1-1.fna.fbcdn.net/v/t39.3...,NaN,Jdtti9iWLTkUGNcQwpQ8h6,UserAccount,['UserAccount'],Joined about a week ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
fb_df_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11829 entries, 0 to 11828
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   11829 non-null  float64
 1   name         11829 non-null  object
 2   link         11829 non-null  object
 3   profile_pic  11826 non-null  object
 4   role         5 non-null      object
 5   id           11829 non-null  object
 6   type         11826 non-null  object
 7   labels       11829 non-null  object
 8   joined       11821 non-null  object
 9   description  6922 non-null   object
 10  lang         6923 non-null   object
 11  location     5337 non-null   object
 12  occupation   196 non-null    object
 13  misc_ents    509 non-null    object
 14  other_ents   74 non-null     object
 15  untagged     1019 non-null   object
dtypes: float64(1), object(15)
memory usage: 1.4+ MB

In [ ]:
#fb_df_v2.to_csv("data-temp/fb_data_langid_semiprocessed_v2.csv", sep="\t")

Even now, after copying the description column value into the location column for each row with an uncaptured non-null description, some rows continue to fall through the NLP pipeline’s cracks. I have noticed a number of rows with Arabic, Lao, Thai, and other non-ASCII languages that have not had their descriptions captured into locations by my code. We turn to those rows now. Below, I retrieve the row counts in each of those languages, and write the records to a CSV for manual OSINT verification. My objective is to determine how many of these uncaptured rows actually reference a real place.

In [21]:
eastern_vals_df = fb_df_v2[(fb_df_v2["description"].str.len() > 3) & ~(fb_df_v2["lang"].isin(["en", "pt", "vi", "id", "ko", "es"])) ]

In [22]:
eastern_vals_df["lang"].value_counts()

be    29
tr    23
ar     9
ru     5
bg     5
he     1
Name: lang, dtype: int64

In [ ]:
#eastern_vals_df.to_csv("data-temp/eastern_values_data.csv", sep="\t")

Manual verification gives the following table of results:

|Language |Yes (mention a real place)  | No (not real place)| Total|
--- | --- | ---| ---|
|Arabic|6 |3 |9|
|Belarusian |5 |22 |29 (2 not yet categorized)|
|Bulgarian |4 |1 |5 |
|Hebrew |1| 0|1 |
|Russian |3 |2 |5|
|Turkish |21 |2 |23|


Interestingly, most of the descriptions classified as Belarusian are actually in English, but written in non-unicode fonts - a good example is "Works at 𝐈𝐍 𝐀 𝐑𝐄𝐋𝐀𝐓𝐈𝐎𝐍𝐒𝐇𝐈𝐏 𝐖𝐈𝐓𝐇 𝐘𝐎𝐔.", which occurs [TODO: GET COUNT] times in the dataset. 

Based on these numbers, I will copy over the description values into the Location column for each of these languages except for Belarusian.

In [23]:
eastern_vals_real = eastern_vals_df[eastern_vals_df["lang"] != "be"]
eastern_vals_real["location"] = eastern_vals_real["description"]
eastern_vals_real.describe()

e:\Users\Eric\miniconda3\envs\arcgis_env\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

         Unnamed: 0
count     43.000000
mean    4705.790698
std     3492.639939
min      126.000000
25%     2186.000000
50%     3256.000000
75%     7320.500000
max    11776.000000

In [24]:
fb_df_v2.update(eastern_vals_real)
# fb_df_v2.to_csv("data-temp/fb_data_langid_semiprocessed_v2.csv", sep="\t")
fb_df_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11829 entries, 0 to 11828
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   11829 non-null  float64
 1   name         11829 non-null  object
 2   link         11829 non-null  object
 3   profile_pic  11826 non-null  object
 4   role         5 non-null      object
 5   id           11829 non-null  object
 6   type         11826 non-null  object
 7   labels       11829 non-null  object
 8   joined       11821 non-null  object
 9   description  6922 non-null   object
 10  lang         6923 non-null   object
 11  location     5348 non-null   object
 12  occupation   196 non-null    object
 13  misc_ents    509 non-null    object
 14  other_ents   74 non-null     object
 15  untagged     1019 non-null   object
dtypes: float64(1), object(15)
memory usage: 1.4+ MB

In [25]:
fb_df_v2.to_csv("data-temp/fb_data_langid_semiprocessed_v2.csv", sep="\t", encoding="utf-8-sig")